import Foundation
import MapKit

/// The published catalog of off-field landability packs — `index.json` at the root of the
/// HuggingFace dataset, generated by `lz/publish.py` from each pack's own MBTiles metadata.
///
/// SHAPED DELIBERATELY UNLIKE `ChartCatalog`, in two ways that matter:
///
///  1. A FLAT `cells` ARRAY, not one array per layer. Chart packs are named FAA sheets and the
///     catalog hard-codes `sectional` / `ifrLow` / `ifrHigh`; landability packs are 1x1 degree
///     cells with nothing but geography to distinguish them, so selection is a rect intersection
///     and grouping is presentational (`regions`) rather than structural.
///
///  2. NO GLOBAL `cycle`. FAA charts run a 56-day AIRAC, so one string dates the whole catalog and
///     `ChartCatalog.provenance` derives an expiry from it. Landability data has no cycle at all:
///     NLCD is annual, 3DEP is whenever a survey flew, and two neighbouring cells can legitimately
///     be built years apart. Staleness is therefore PER PACK, via `builtAt` and the vintages the
///     pack itself carries — asking "is the catalog current" is not a question with an answer here.
struct LZPackCatalog: Decodable {

    /// Catalog format this build understands. A newer catalog is REFUSED rather than half-read:
    /// same doctrine as `LZPackStore` refusing a newer pack schema. Silently ignoring fields we do
    /// not know is how a pilot ends up with a subtly wrong offer.
    static let supportedSchema = 1

    let schema: Int
    let regions: [Region]
    let cells: [Cell]

    /// A named grouping the Downloads screen offers as a unit. Purely presentational — a pilot does
    /// not think in degree cells, but the cell stays the download unit because it is what the
    /// pipeline emits and what the app mounts.
    struct Region: Decodable, Identifiable, Equatable {
        let id: String
        let title: String
        let note: String?
        /// Cell ids, in the order the publisher listed them.
        let cells: [String]
    }

    struct Cell: Decodable, Identifiable, Equatable, Hashable {
        let id: String                  // "n33w107" — USGS 3DEP naming, NW corner
        let path: String                // "cells/n33w107.lzpack", relative to the repo root
        let bytes: Int
        /// Published so an 88 MB download can be checked. The chart catalog has none — integrity
        /// there is behavioural ("does it open as MBTiles") — which is a thin guarantee at this size.
        let sha256: String?
        let bounds: [Double]            // [west, south, east, north] — same order as ChartCatalog
        let builtAt: String?
        /// Pack format. Absent on catalogs published before it was recorded, which were all
        /// schema 1 — so the default is the honest reading rather than an optimistic one.
        let schemaRaw: Int?
        var schema: Int { schemaRaw ?? 1 }
        /// Whether THIS build can read the pack. Checked before offering the download, because
        /// finding out afterwards costs the pilot 90 MB and tells them nothing useful.
        var isReadable: Bool { LZPack.readableSchemas.contains(schema) }
        /// How many tiles in this cell had only 10 m elevation, where the ditch- and berm-scale
        /// checks CANNOT run and the score is capped instead. Surfaced before the download, so
        /// "this region is partly coarse" is knowable without spending the bytes.
        let coarseTerrainTiles: Int?

        private enum CodingKeys: String, CodingKey {
            case id, path, bytes, sha256, bounds
            case builtAt = "built_at"
            case schemaRaw = "schema"
            case coarseTerrainTiles = "coarse_terrain_tiles"
        }

        static func == (a: Cell, b: Cell) -> Bool { a.id == b.id }
        func hash(into h: inout Hasher) { h.combine(id) }

        /// The footprint, for rect-intersection selection. Nil rather than a guess when the bounds
        /// are unusable — an entry that cannot say where it is must not be offered as coverage.
        var mapRect: MKMapRect? {
            guard bounds.count == 4 else { return nil }
            let (w, s, e, n) = (bounds[0], bounds[1], bounds[2], bounds[3])
            guard w.isFinite, s.isFinite, e.isFinite, n.isFinite, w < e, s < n else { return nil }
            let a = MKMapPoint(CLLocationCoordinate2D(latitude: n, longitude: w))
            let b = MKMapPoint(CLLocationCoordinate2D(latitude: s, longitude: e))
            return MKMapRect(x: min(a.x, b.x), y: min(a.y, b.y),
                             width: abs(b.x - a.x), height: abs(b.y - a.y))
        }

        /// Where the pack lands on disk. The filename IS the id: unlike chart packs there is no
        /// cycle to encode, because there is no cycle. That is what makes the id derivation here
        /// trivial where `ChartLibrary.packID` had to strip a date by shape — and it is why a
        /// future cycle-like suffix must NOT be bolted onto the filename.
        var localFilename: String { "\(id).lzpack" }

        func remote(base: String) -> URL? {
            guard !path.isEmpty, !path.hasPrefix("/"), !path.contains("..") else { return nil }
            return URL(string: "\(base)/\(path)")
                ?? path.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed)
                       .flatMap { URL(string: "\(base)/\($0)") }
        }
    }

    /// Cells whose footprint meets any of `rects` — the selection the route and viewport offers use.
    /// Mirrors `ChartLibrary`'s chart-side filter, which is the same one-line rect intersection.
    func cells(intersecting rects: [MKMapRect]) -> [Cell] {
        guard !rects.isEmpty else { return [] }
        return cells.filter { c in
            guard c.isReadable, let r = c.mapRect else { return false }
            return rects.contains { $0.intersects(r) }
        }
    }

    func cell(id: String) -> Cell? { cells.first { $0.id == id } }

    /// Cells a region names AND the catalog actually publishes, in the region's order. A region
    /// listing a cell that does not exist yet is normal — coverage grows one build at a time.
    func cells(in region: Region) -> [Cell] {
        region.cells.compactMap { id in cells.first { $0.id == id && $0.isReadable } }
    }

    var totalBytes: Int { cells.reduce(0) { $0 + $1.bytes } }

    /// Decode + schema gate in one place, so no caller can forget the gate.
    static func decode(_ data: Data) -> LZPackCatalog? {
        guard let c = try? JSONDecoder().decode(LZPackCatalog.self, from: data) else { return nil }
        guard c.schema == supportedSchema else { return nil }
        return c
    }
}
