import XCTest
import SQLite3
@testable import ATCTranscribe

/// Contract tests for the `.lzpack` fact-tile reader.
///
/// The fixture is generated by `lz/package.py --fixture`, so these tests prove the CROSS-LANGUAGE
/// contract: Python writes the blob, Swift reads it. A Swift-generated fixture would only prove
/// Swift agrees with itself, which is precisely the bug class that matters here — the packer and
/// the decoder drifting on framing (raw DEFLATE vs zlib) or row order (XYZ vs TMS). Both of those
/// failures are SILENT: the layer renders transparent, or mirrored, with no error anywhere.
final class LZPackTests: XCTestCase {

    private var packURL: URL!

    // The fixture's four tiles, from lz/package.py --fixture.
    private let z = 13
    private let x0 = 1000, y0 = 2000

    override func setUpWithError() throws {
        packURL = try XCTUnwrap(Bundle(for: Self.self).url(forResource: "lz_fixture",
                                                           withExtension: "lzpack"),
                                "lz_fixture.lzpack missing from the test bundle")
    }

    private func store() throws -> LZPackStore {
        let dir = FileManager.default.temporaryDirectory
            .appendingPathComponent("lztest-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        try FileManager.default.copyItem(at: packURL, to: dir.appendingPathComponent("fixture.lzpack"))
        return LZPackStore(directory: dir)
    }

    // MARK: - decode

    func testFixtureTileDecodesToSixFullPlanes() throws {
        let s = try store()
        XCTAssertTrue(s.isAvailable, "fixture pack did not mount: \(s.rejected)")
        let t = try XCTUnwrap(s.planes(z: z, x: x0, y: y0), "no tile at the fixture address")
        XCTAssertEqual(t.planes.count, LZPack.planeCount)
        for p in t.planes {
            XCTAssertEqual(p.count, LZPack.planeBytes, "a plane decoded to the wrong length")
        }
        // Tile 1 is a clean open field on fine terrain.
        XCTAssertEqual(t.value(plane: LZPack.planeClass, x: 128, y: 128), LZPack.classOpenFirm)
        XCTAssertEqual(t.value(plane: LZPack.planeConf, x: 128, y: 128), 80)
        XCTAssertEqual(t.terrainSource, LZPack.terrainFine)
        XCTAssertFalse(t.isCoarseTerrain)
    }

    /// Orientation. The packer marks the NORTH-WEST pixel and the SOUTH-EAST pixel with distinct
    /// classes. If the TMS row flip were applied twice (or not at all) the tile would still decode,
    /// still have the right byte count, and be mirrored north-for-south — so this is the only
    /// assertion that actually catches it.
    func testRowOrderSurvivesTheTMSFlip() throws {
        let s = try store()
        let t = try XCTUnwrap(s.planes(z: z, x: x0, y: y0))
        XCTAssertEqual(t.value(plane: LZPack.planeClass, x: 0, y: 0),
                       LZPack.classDevelopedOpen, "north-west corner is wrong — row order flipped")
        XCTAssertEqual(t.value(plane: LZPack.planeClass, x: LZPack.side - 1, y: LZPack.side - 1),
                       LZPack.classBrush, "south-east corner is wrong — row order flipped")
    }

    func testAllFourFixtureTilesAreAddressable() throws {
        let s = try store()
        for (dx, dy) in [(0, 0), (1, 0), (0, 1), (1, 1)] {
            XCTAssertNotNil(s.planes(z: z, x: x0 + dx, y: y0 + dy),
                            "missing fixture tile at +\(dx),+\(dy)")
        }
        XCTAssertNil(s.planes(z: z, x: x0 + 9, y: y0 + 9), "returned a tile that does not exist")
    }

    /// The coarse-DEM tile. 3DEP 1 m covers 100% of the shipping cell, so NOTHING in the real pack
    /// exercises the cap that stops un-vetoable 10 m terrain from outscoring lidar-covered ground.
    /// The fixture carries this tile so that rule is testable at all.
    func testCoarseTerrainTileIsDistinguishable() throws {
        let s = try store()
        let fine = try XCTUnwrap(s.planes(z: z, x: x0, y: y0))
        let coarse = try XCTUnwrap(s.planes(z: z, x: x0, y: y0 + 1))
        XCTAssertEqual(coarse.terrainSource, LZPack.terrainCoarse)
        XCTAssertTrue(coarse.isCoarseTerrain)
        XCTAssertFalse(fine.isCoarseTerrain)
        // Same surface facts, different provenance — so only the cap can separate them.
        XCTAssertEqual(coarse.value(plane: LZPack.planeClass, x: 10, y: 10),
                       fine.value(plane: LZPack.planeClass, x: 10, y: 10))
        let flags = try XCTUnwrap(coarse.value(plane: LZPack.planeFlags, x: 10, y: 10))
        XCTAssertEqual(flags & LZPack.flagCoarseTerrain, LZPack.flagCoarseTerrain)
    }

    func testWaterAndWireFixtureTilesCarryTheirFlags() throws {
        let s = try store()
        let water = try XCTUnwrap(s.planes(z: z, x: x0 + 1, y: y0))
        XCTAssertEqual(water.value(plane: LZPack.planeClass, x: 5, y: 5), LZPack.classWater)
        let wf = try XCTUnwrap(water.value(plane: LZPack.planeFlags, x: 5, y: 5))
        XCTAssertEqual(wf & LZPack.flagWaterVeto, LZPack.flagWaterVeto)

        let wire = try XCTUnwrap(s.planes(z: z, x: x0 + 1, y: y0 + 1))
        XCTAssertEqual(wire.value(plane: LZPack.planeHazard, x: 5, y: 5), 220)
        let f = try XCTUnwrap(wire.value(plane: LZPack.planeFlags, x: 5, y: 5))
        XCTAssertEqual(f & LZPack.flagTXCorridor, LZPack.flagTXCorridor)
    }

    // MARK: - corruption must degrade, never trap

    private func fixtureBlob() throws -> Data {
        var db: OpaquePointer?
        XCTAssertEqual(sqlite3_open_v2(packURL.path, &db, SQLITE_OPEN_READONLY, nil), SQLITE_OK)
        defer { sqlite3_close(db) }
        var st: OpaquePointer?
        XCTAssertEqual(sqlite3_prepare_v2(db, "select tile_data from tiles limit 1", -1, &st, nil),
                       SQLITE_OK)
        defer { sqlite3_finalize(st) }
        XCTAssertEqual(sqlite3_step(st), SQLITE_ROW)
        let blob = try XCTUnwrap(sqlite3_column_blob(st, 0))
        return Data(bytes: blob, count: Int(sqlite3_column_bytes(st, 0)))
    }

    func testTruncationAtEveryPrefixReturnsNilAndNeverTraps() throws {
        let full = try fixtureBlob()
        XCTAssertNotNil(LZPackBlob.decode(full), "the intact blob must decode")
        // Every prefix shorter than the whole blob is corrupt by construction. Walk all of them:
        // an off-by-one in the header maths shows up at exactly one length, and a spot check of
        // three sizes would miss it.
        for n in 0..<full.count {
            XCTAssertNil(LZPackBlob.decode(full.prefix(n)),
                         "a \(n)-byte prefix decoded — bounds check is wrong")
        }
    }

    func testWrongMagicVersionOrPlaneCountIsRefused() throws {
        let full = try fixtureBlob()
        var bad = full
        bad[0] = 0x58                                   // magic
        XCTAssertNil(LZPackBlob.decode(bad))
        bad = full; bad[4] = LZPack.version &+ 1        // version
        XCTAssertNil(LZPackBlob.decode(bad), "an unknown version must be refused, not guessed")
        // DERIVED, not the literal 7 — which is what this was, and became the CORRECT plane count
        // when the extent plane landed, so the test started asserting that a valid blob is refused.
        bad = full; bad[5] = UInt8(LZPack.planeCount &+ 1)
        XCTAssertNil(LZPackBlob.decode(bad), "a blob claiming more planes than we know must be refused")
        bad = full; bad[5] = UInt8(LZPack.planeCount &- 1)
        XCTAssertNil(LZPackBlob.decode(bad), "a blob claiming fewer planes must be refused too")
        bad = full; bad[6] = 0x80; bad[7] = 0x00        // side = 128
        XCTAssertNil(LZPackBlob.decode(bad))
        bad = full; bad[8] = 9                          // impossible terrain source
        XCTAssertNil(LZPackBlob.decode(bad))
    }

    func testAbsurdPlaneLengthIsRefusedRatherThanAllocated() throws {
        let full = try fixtureBlob()
        var bad = full
        // First plane length = 0xFFFFFFFF. A decoder that trusts this either over-reads or tries
        // to allocate 4 GB; it must simply say no.
        for i in 0..<4 { bad[LZPack.headerFixed + i] = 0xFF }
        XCTAssertNil(LZPackBlob.decode(bad))
    }

    func testCorruptDeflateStreamReturnsNil() throws {
        let full = try fixtureBlob()
        var bad = full
        // Scribble over the middle of the compressed payload, leaving all lengths intact.
        let mid = LZPack.headerBytes + (full.count - LZPack.headerBytes) / 2
        for i in mid..<min(mid + 16, bad.count) { bad[i] = 0x5A }
        // Either it fails to inflate or it inflates to the wrong size; both must be nil.
        XCTAssertNil(LZPackBlob.decode(bad))
    }

    // MARK: - store mounting rules

    func testOnlyLzpackFilesAreMounted() throws {
        let dir = FileManager.default.temporaryDirectory
            .appendingPathComponent("lztest-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        try FileManager.default.copyItem(at: packURL, to: dir.appendingPathComponent("a.lzpack"))
        // A chart pack sitting in the same folder must not be mounted as fact tiles.
        try FileManager.default.copyItem(at: packURL, to: dir.appendingPathComponent("chart.mbtiles"))
        try Data("not a database".utf8).write(to: dir.appendingPathComponent("notes.txt"))
        let s = LZPackStore(directory: dir)
        XCTAssertEqual(s.readers.count, 1, "expected exactly the .lzpack to mount")
    }

    /// A pack from a newer pipeline must be REFUSED, not read as garbage — and the refusal has to
    /// be visible so the UI can explain an empty layer instead of silently showing nothing.
    func testFuturePackSchemaIsRefusedWithAReason() throws {
        let dir = FileManager.default.temporaryDirectory
            .appendingPathComponent("lztest-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        let dst = dir.appendingPathComponent("future.lzpack")
        try FileManager.default.copyItem(at: packURL, to: dst)

        var db: OpaquePointer?
        XCTAssertEqual(sqlite3_open_v2(dst.path, &db, SQLITE_OPEN_READWRITE, nil), SQLITE_OK)
        XCTAssertEqual(sqlite3_exec(db, "update metadata set value='99' where name='lz_schema'",
                                    nil, nil, nil), SQLITE_OK)
        sqlite3_close(db)

        let s = LZPackStore(directory: dir)
        XCTAssertFalse(s.isAvailable, "a future-schema pack must not mount")
        XCTAssertEqual(s.rejected.count, 1)
        XCTAssertTrue(s.rejected[0].contains("schema"), "rejection should name the reason")
    }

    func testMissingDirectoryYieldsAnEmptyStoreNotACrash() {
        let dir = FileManager.default.temporaryDirectory
            .appendingPathComponent("lz-absent-\(UUID().uuidString)", isDirectory: true)
        let s = LZPackStore(directory: dir)
        XCTAssertFalse(s.isAvailable)
        XCTAssertNil(s.planes(z: 13, x: 1, y: 1))
    }

    // MARK: - quantisation helpers

    func testSlopeAndRoughDecodeMatchThePackersQuantisation() {
        XCTAssertEqual(LZPack.slopeDegrees(0), 0.0)
        XCTAssertEqual(try XCTUnwrap(LZPack.slopeDegrees(10)), 2.0, accuracy: 1e-9)
        XCTAssertEqual(try XCTUnwrap(LZPack.slopeDegrees(254)), 50.8, accuracy: 1e-9)
        XCTAssertNil(LZPack.slopeDegrees(LZPack.slopeNoData),
                     "nodata must not decode to a real slope")
        XCTAssertEqual(try XCTUnwrap(LZPack.roughMetres(5)), 0.05, accuracy: 1e-9)
        XCTAssertNil(LZPack.roughMetres(LZPack.roughNoData))
    }

    /// Nodata is 255 for both slope and roughness, and 255 is also a legal-looking byte. The
    /// decoder must map it to nil rather than to a very steep, very rough cell — or a hole in the
    /// DEM would render as the worst ground on the map instead of as unknown.
    func testNoDataIsNotMistakenForAnExtremeValue() {
        XCTAssertNil(LZPack.slopeDegrees(255))
        XCTAssertNil(LZPack.roughMetres(255))
        XCTAssertNotNil(LZPack.slopeDegrees(254))
        XCTAssertNotNil(LZPack.roughMetres(254))
    }
}
