import XCTest
@testable import ATCTranscribe

/// Byte-parity of the Swift snap stages against the Python reference — replays
/// `snap_fixtures.json` (generated by `Tools/gen_snap_fixtures.py` from
/// `python-legacy/callsign_snap.py` + `slot_snap.py`) and asserts identical text + verdicts.
final class SnapParityTests: XCTestCase {

    struct Fixtures: Decodable {
        struct CS: Decodable {
            let `in`: String, out: String, verdict: String
            let original: String?, snapped: String?, applied: Bool
        }
        struct SlotCase: Decodable {
            struct E: Decodable {
                let slot: String, verdict: String, original: String
                let snapped: String?, applied: Bool
            }
            let `in`: String, out: String, edits: [E]
        }
        let callsign: [CS]
        let slots: [SlotCase]
        let cs_candidates: [String]
        let slot_ctx: Ctx
        struct Ctx: Decodable {
            let ident: String
            let runways: [String]
            let frequencies: [String: [Double]]
        }
    }

    private func load() throws -> Fixtures {
        let url = try XCTUnwrap(Bundle(for: Self.self).url(forResource: "snap_fixtures",
                                                           withExtension: "json"),
                                "snap_fixtures.json missing from the test bundle")
        return try JSONDecoder().decode(Fixtures.self, from: Data(contentsOf: url))
    }

    /// The fixtures' candidate telephony words are all majors in the embedded fallback set, so
    /// parity does not depend on the airlines.json load (pass nil knowledge deliberately).
    func testCallsignParity() throws {
        let fx = try load()
        let telephony = CallsignSnap.telephonyWords(nil)
        for c in fx.callsign {
            let (text, result) = CallsignSnap.snapTranscript(c.in, candidates: fx.cs_candidates,
                                                             telephony: telephony)
            XCTAssertEqual(text, c.out, "text mismatch for: \(c.in)")
            XCTAssertEqual(result.verdict, c.verdict, "verdict mismatch for: \(c.in)")
            XCTAssertEqual(result.original, c.original, "original mismatch for: \(c.in)")
            XCTAssertEqual(result.snapped, c.snapped, "snapped mismatch for: \(c.in)")
            XCTAssertEqual(result.applied, c.applied, "applied mismatch for: \(c.in)")
        }
    }

    func testSlotParity() throws {
        let fx = try load()
        let ctx = AirportContextData(ident: fx.slot_ctx.ident, runways: fx.slot_ctx.runways,
                                     frequencies: fx.slot_ctx.frequencies)
        for c in fx.slots {
            let (text, edits) = SlotSnap.apply(c.in, context: ctx)
            XCTAssertEqual(text, c.out, "text mismatch for: \(c.in)")
            XCTAssertEqual(edits.count, c.edits.count, "edit count mismatch for: \(c.in) — \(edits)")
            for (e, expected) in zip(edits, c.edits) {
                XCTAssertEqual(e.slot, expected.slot, "slot for: \(c.in)")
                XCTAssertEqual(e.verdict, expected.verdict, "verdict for: \(c.in)")
                XCTAssertEqual(e.original, expected.original, "original for: \(c.in)")
                XCTAssertEqual(e.snapped, expected.snapped, "snapped for: \(c.in)")
                XCTAssertEqual(e.applied, expected.applied, "applied for: \(c.in)")
            }
        }
    }

    func testNoContextCanonicalizesOnly() {
        let (text, edits) = SlotSnap.apply("cleared to land runway one eight right", context: nil)
        XCTAssertTrue(edits.isEmpty)
        XCTAssertEqual(text, "cleared to land runway 1 8 right")
    }
}
