import XCTest
@testable import ATCTranscribe

/// TurnRoleTagger: parity with the Python `atc_diarize.classify_turn` reference (via
/// `role_fixtures.json`, generated by `Tools/gen_role_fixtures.py`) plus behavior spot-checks.
final class TurnRoleTaggerTests: XCTestCase {

    struct Fixture: Decodable { let `in`: String; let role: String; let confidence: Double }

    func testPythonParity() throws {
        let url = try XCTUnwrap(Bundle(for: Self.self).url(forResource: "role_fixtures",
                                                          withExtension: "json"),
                                "role_fixtures.json missing from the test bundle")
        let fixtures = try JSONDecoder().decode([Fixture].self, from: Data(contentsOf: url))
        XCTAssertGreaterThan(fixtures.count, 10)
        for f in fixtures {
            let got = TurnRoleTagger.classify(f.in, knowledge: nil)
            XCTAssertEqual(got.role.rawValue, f.role, "role mismatch for: \(f.in)")
            XCTAssertEqual(got.confidence, f.confidence, accuracy: 1e-6, "confidence for: \(f.in)")
        }
    }

    func testControllerInstruction() {
        XCTAssertEqual(TurnRoleTagger.classify("delta 232 cleared to land runway 22 right",
                                               knowledge: nil).role, .controller)
    }

    func testPilotReadbackTag() {
        XCTAssertEqual(TurnRoleTagger.classify("with you at 5000 american 88",
                                               knowledge: nil).role, .pilot)
    }

    func testAmbiguousIsUnknown() {
        // no cue on either side
        XCTAssertEqual(TurnRoleTagger.classify("and that is all the traffic i have for you",
                                               knowledge: nil).role, .unknown)
    }

    func testEmptyIsUnknown() {
        XCTAssertEqual(TurnRoleTagger.classify("", knowledge: nil).role, .unknown)
        XCTAssertEqual(TurnRoleTagger.classify("!!!", knowledge: nil).role, .unknown)
    }

    func testSubstringCueNotDoubleCounted() {
        // "cleared to land" must not also count "cleared" — mirror of _count_cues distinctness
        XCTAssertEqual(TurnRoleTagger.countCues("cleared to land", TurnRoleTagger.controllerCues), 1)
    }

    func testTrailingCallsignDetected() {
        let tokens = "southwest 2914 left heading 270".split(separator: " ").map(String.init)
        XCTAssertFalse(TurnRoleTagger.callsignIsTrailing(tokens: tokens, callsign: "southwest 2914"))
        let tokens2 = "left heading 270 southwest 2914".split(separator: " ").map(String.init)
        XCTAssertTrue(TurnRoleTagger.callsignIsTrailing(tokens: tokens2, callsign: "southwest 2914"))
    }
}
